### ISSUE TITLE
Support serviceAccount

### ISSUE THREAD

**Issue by hongbo-miao** [HelloOraculi/helm#21]
It would be great to support passing `serviceAccount` section like other Helm charts such as https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml#L751-L764.

So it would be something like

```yaml
image:
  repository: docker.io/tailwarden/komiser
  tag: 3.1.18
aws:
  region: us-west-2
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxxxxx:role/KomiserRole-hm-komiser
```

Thanks! ☺️
