### ISSUE TITLE
Support externalDatabase

### ISSUE THREAD

**Issue by hongbo-miao** [HelloOraculi/helm#22]
It would be great to support passing `serviceAccount` section like other Helm charts such as https://github.com/bitnami/charts/blob/main/bitnami/mlflow/values.yaml#L751-L764.

So it would be something like

```yaml
image:
  repository: docker.io/tailwarden/komiser
  tag: 3.1.18
aws:
  region: us-west-2
externalDatabase:
  dialectDriver: postgresql
  host: production-hm-komiser-postgres.xxx.us-west-2.rds.amazonaws.com
  port: 5432
  database: komiser_db
  user: komiser_user
  existingSecret: hm-komiser-secret
  existingSecretPasswordKey: komiser_password
```

Thanks! ☺️
